-- Actualiza la columna `regional` de cada CAV en
-- "Schemas_Herramienta_Trade_gastos".cavs segun el centro de costos.
-- Idempotente: se puede ejecutar varias veces y siempre deja el valor correcto.

BEGIN;

UPDATE "Schemas_Herramienta_Trade_gastos".cavs AS c
SET regional = v.regional
FROM (
    VALUES
        ('C114', 'Zona Sur'),
        ('C159', 'Zona Norte'),
        ('C502', 'Zona Norte'),
        ('C501', 'Zona Norte'),
        ('C106', 'Zona Norte'),
        ('C116', 'Zona Norte'),
        ('C176', 'Zona Sur'),
        ('C102', 'Zona Norte'),
        ('C109', 'Zona Sur'),
        ('C153', 'Zona Sur'),
        ('C110', 'Zona Norte'),
        ('C111', 'Zona Sur'),
        ('C108', 'Plaza Claro'),
        ('C157', 'Zona Sur'),
        ('C103', 'Zona Sur'),
        ('C133', 'Zona Norte'),
        ('C155', 'Zona Norte'),
        ('C105', 'Zona Sur'),
        ('C182', 'Zona Norte'),
        ('C309', 'Fuera de Coltrade'),
        ('C507', 'Zona Norte'),
        ('C311', 'Fuera de Coltrade'),
        ('C312', 'Zona Sur'),
        ('C181', 'Fuera de Coltrade'),
        ('C192', 'Zona Norte'),
        ('C123', 'Zona Norte'),
        ('C303', 'Zona Sur'),
        ('C300', 'Zona Sur'),
        ('C301', 'Zona Sur'),
        ('C305', 'Zona Sur'),
        ('C508', 'Zona Sur'),
        ('C125', 'Zona Norte'),
        ('C318', 'Fuera de Coltrade'),
        ('C173', 'Zona Norte'),
        ('C321', 'Zona Norte'),
        ('C510', 'Zona Norte'),
        ('C511', 'Zona Norte'),
        ('C104', 'Zona Sur'),
        ('C107', 'Zona Norte'),
        ('C577', 'Zona Sur'),
        ('C302', 'Zona Sur'),
        ('C131', 'Zona Sur'),
        ('C130', 'Fuera de Coltrade'),
        ('C120', 'Zona Norte'),
        ('C185', 'Fuera de Coltrade'),
        ('C506', 'Fuera de Coltrade'),
        ('C121', 'Fuera de Coltrade'),
        ('C178', 'Fuera de Coltrade'),
        ('C304', 'Fuera de Coltrade'),
        ('C179', 'Fuera de Coltrade'),
        ('C154', 'Fuera de Coltrade'),
        ('C505', 'Fuera de Coltrade'),
        ('C322', 'Fuera de Coltrade'),
        ('C319', 'Fuera de Coltrade'),
        ('C220', 'Fuera de Coltrade'),
        ('C327', 'Fuera de Coltrade'),
        ('C186', 'Fuera de Coltrade'),
        ('C126', 'Fuera de Coltrade'),
        ('C324', 'Fuera de Coltrade'),
        ('C308', 'Fuera de Coltrade'),
        ('C115', 'Fuera de Coltrade'),
        ('C320', 'Fuera de Coltrade'),
        ('C375', 'Fuera de Coltrade'),
        ('C160', 'Fuera de Coltrade'),
        ('C277', 'Fuera de Coltrade'),
        ('C550', 'Fuera de Coltrade'),
        ('C350', 'Fuera de Coltrade'),
        ('C383', 'Fuera de Coltrade'),
        ('C325', 'Fuera de Coltrade'),
        ('C315', 'Fuera de Coltrade'),
        ('C198', 'Fuera de Coltrade'),
        ('C190', 'Fuera de Coltrade'),
        ('C175', 'Fuera de Coltrade'),
        ('C578', 'Fuera de Coltrade'),
        ('C390', 'Fuera de Coltrade'),
        ('C224', 'Fuera de Coltrade'),
        ('C221', 'Fuera de Coltrade'),
        ('C382', 'Fuera de Coltrade'),
        ('C124', 'Fuera de Coltrade'),
        ('C326', 'Fuera de Coltrade'),
        ('C128', 'Fuera de Coltrade'),
        ('C555', 'Fuera de Coltrade'),
        ('C132', 'Fuera de Coltrade'),
        ('C503', 'Fuera de Coltrade'),
        ('C197', 'Fuera de Coltrade'),
        ('C370', 'Fuera de Coltrade'),
        ('C359', 'Fuera de Coltrade'),
        ('C172', 'Fuera de Coltrade'),
        ('C500', 'Zona Norte')
) AS v(centro_costos, regional)
WHERE TRIM(c.centro_costos) = v.centro_costos;

-- Validacion: lista los CAV que quedaron sin regional asignada
-- (deberian ser cero si todos los centros de costos del listado existen).
-- SELECT centro_costos, nombre_cav FROM "Schemas_Herramienta_Trade_gastos".cavs WHERE regional IS NULL;

COMMIT;
